- name: Run frontend container
  docker_container:
    name: my_frontend
    image: hissein/tp-devops-frontend
    pull: true
    recreate: true
    force_kill: true
    networks:
      - name: httpd_network
    state: started