- name: Run API app container (connected to both networks)
  docker_container:
    name: simple-api
    image: hissein/tp-devops-simple-api
    pull: true
    recreate: true
    force_kill: true
    networks:
      - name: backend_network
      - name: httpd_network
    env:
      SPRING_DATASOURCE_URL: jdbc:postgresql://my_postgres:5432/{{POSTGRES_DB}}
      SPRING_DATASOURCE_USERNAME: "{{POSTGRES_USER}}"
      SPRING_DATASOURCE_PASSWORD: "{{POSTGRES_PASSWORD}}"
    state: started
    restart_policy: always