services:
  database:
    build:
      context: ./database
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  backend-api:
    build:
      context: ./backend-api
    depends_on:
      - database
    networks:
      - app-network
    ports:
      - "8080:8080"
    restart: unless-stopped

  httpd:
    build:
      context: ./http-server
    depends_on:
      - backend-api
    networks:
      - app-network
    ports:
      - "80:80"
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
