name: Deploy on Main Push

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Add SSH private key
        run: |
          echo "${{ secrets.DEPLOY_KEY }}" > id_rsa
          chmod 600 id_rsa

      - name: Deploy with Ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
        run: |
          echo "${{ secrets.VAULT_PASS }}" > vault_pass.txt
          ansible-playbook -i tp3/ansible/inventories/setup.yml tp3/ansible/playbook.yml --vault-password-file vault_pass.txt
          rm vault_pass.txt